--------------------------------------------------------
--  Fichier créé - dimanche-avril-11-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BLOCS
--------------------------------------------------------

  CREATE TABLE "AYMEN"."BLOCS" 
   (	"IDBLOCS" VARCHAR2(1000 BYTE), 
	"NUMB" VARCHAR2(1000 BYTE), 
	"ETAT" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BOISSON
--------------------------------------------------------

  CREATE TABLE "AYMEN"."BOISSON" 
   (	"ID" VARCHAR2(1000 BYTE), 
	"TYPE" VARCHAR2(1000 BYTE), 
	"NOM" VARCHAR2(1000 BYTE), 
	"INGREDIENTS" VARCHAR2(1000 BYTE), 
	"PRIX" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "AYMEN"."CLIENT" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(20 BYTE), 
	"TEL" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COLLABORATEUR
--------------------------------------------------------

  CREATE TABLE "AYMEN"."COLLABORATEUR" 
   (	"TELEPHONE" VARCHAR2(1000 BYTE), 
	"PRENOM" VARCHAR2(1000 BYTE), 
	"NOM" VARCHAR2(1000 BYTE), 
	"IDCOLLABORATEUR" VARCHAR2(1000 BYTE), 
	"EMAIL" VARCHAR2(1000 BYTE), 
	"COLUMN6" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMMANDE
--------------------------------------------------------

  CREATE TABLE "AYMEN"."COMMANDE" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"CINP" VARCHAR2(20 BYTE), 
	"PRIX" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CONTRAT
--------------------------------------------------------

  CREATE TABLE "AYMEN"."CONTRAT" 
   (	"TYPE" VARCHAR2(1000 BYTE), 
	"TARIF" VARCHAR2(1000 BYTE), 
	"NOM" VARCHAR2(1000 BYTE), 
	"IDCOLLABORATEUR" VARCHAR2(1000 BYTE), 
	"DUREE" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EM
--------------------------------------------------------

  CREATE TABLE "AYMEN"."EM" 
   (	"CIN" VARCHAR2(1000 BYTE), 
	"NOM" VARCHAR2(1000 BYTE), 
	"PRENOM" VARCHAR2(1000 BYTE), 
	"TYPEFONCTION" VARCHAR2(1000 BYTE), 
	"TELEPHONE" VARCHAR2(1000 BYTE), 
	"EMAIL" VARCHAR2(1000 BYTE), 
	"ADRESS" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FC
--------------------------------------------------------

  CREATE TABLE "AYMEN"."FC" 
   (	"TYPEFONCTION" VARCHAR2(1000 BYTE), 
	"SALAIRE" VARCHAR2(1000 BYTE), 
	"JOURDETRAVAIL" VARCHAR2(1000 BYTE), 
	"HEUREDEDEBUT" VARCHAR2(20 BYTE), 
	"HEUREDEFIN" VARCHAR2(20 BYTE), 
	"DEBUTDECONGE" DATE, 
	"FINDECONGE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FOURNISSEUR
--------------------------------------------------------

  CREATE TABLE "AYMEN"."FOURNISSEUR" 
   (	"CINF" VARCHAR2(1000 BYTE), 
	"NOM" VARCHAR2(1000 BYTE), 
	"PRENOM" VARCHAR2(1000 BYTE), 
	"TYPE" VARCHAR2(1000 BYTE), 
	"TEL" VARCHAR2(1000 BYTE), 
	"ADRESSE" VARCHAR2(1000 BYTE), 
	"EMAIL" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MATERIEL
--------------------------------------------------------

  CREATE TABLE "AYMEN"."MATERIEL" 
   (	"ID" VARCHAR2(1000 BYTE), 
	"NOM" VARCHAR2(1000 BYTE), 
	"TYPE" VARCHAR2(1000 BYTE), 
	"MARQUE" VARCHAR2(1000 BYTE), 
	"PRIX" VARCHAR2(1000 BYTE), 
	"CINF" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PLAT
--------------------------------------------------------

  CREATE TABLE "AYMEN"."PLAT" 
   (	"ID" VARCHAR2(1000 BYTE), 
	"TYPE" VARCHAR2(1000 BYTE), 
	"NOM" VARCHAR2(1000 BYTE), 
	"INGREDIENTS" VARCHAR2(1000 BYTE), 
	"PRIX" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUIT
--------------------------------------------------------

  CREATE TABLE "AYMEN"."PRODUIT" 
   (	"ID" VARCHAR2(1000 BYTE), 
	"NOM" VARCHAR2(1000 BYTE), 
	"TYPE" VARCHAR2(1000 BYTE), 
	"MARQUE" VARCHAR2(1000 BYTE), 
	"PRIX" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into AYMEN.BLOCS
SET DEFINE OFF;
REM INSERTING into AYMEN.BOISSON
SET DEFINE OFF;
REM INSERTING into AYMEN.CLIENT
SET DEFINE OFF;
Insert into AYMEN.CLIENT (ID,NOM,PRENOM,ADRESSE,TEL,EMAIL) values ('156','yuety','rtytr','tyt','ytyt','tytyty');
Insert into AYMEN.CLIENT (ID,NOM,PRENOM,ADRESSE,TEL,EMAIL) values ('846','aymen','zefd','azezae','zerez','azeaze');
Insert into AYMEN.CLIENT (ID,NOM,PRENOM,ADRESSE,TEL,EMAIL) values ('4545','azaz','sedrfesdrf','DFGFD','21545','dfgfdgfg');
REM INSERTING into AYMEN.COLLABORATEUR
SET DEFINE OFF;
REM INSERTING into AYMEN.COMMANDE
SET DEFINE OFF;
Insert into AYMEN.COMMANDE (ID,NOM,TYPE,CINP,PRIX) values ('9494','aymen','zezr','5645','456');
Insert into AYMEN.COMMANDE (ID,NOM,TYPE,CINP,PRIX) values ('546546','fdgfd','fgdfg','dfgfdg','gfgfdg');
Insert into AYMEN.COMMANDE (ID,NOM,TYPE,CINP,PRIX) values ('54545','azaez','azez','21245','45');
REM INSERTING into AYMEN.CONTRAT
SET DEFINE OFF;
REM INSERTING into AYMEN.EM
SET DEFINE OFF;
Insert into AYMEN.EM (CIN,NOM,PRENOM,TYPEFONCTION,TELEPHONE,EMAIL,ADRESS) values ('11023658','abid','aymen','Chef','21456398','aymen.abid@gmail.com','sfax');
Insert into AYMEN.EM (CIN,NOM,PRENOM,TYPEFONCTION,TELEPHONE,EMAIL,ADRESS) values ('11145869','Sara','Elarbi','femme de menage','22456811','Saraelarbi@esprit.com','Manzeh5');
Insert into AYMEN.EM (CIN,NOM,PRENOM,TYPEFONCTION,TELEPHONE,EMAIL,ADRESS) values ('11229658','barkia','mohamed','livreur','44518295','mohamed.barkia@esprit.tn','raoued');
Insert into AYMEN.EM (CIN,NOM,PRENOM,TYPEFONCTION,TELEPHONE,EMAIL,ADRESS) values ('14226235','Abid','Aymen','serveur','20365988','aymen.abid@esprit.tn','sfax');
Insert into AYMEN.EM (CIN,NOM,PRENOM,TYPEFONCTION,TELEPHONE,EMAIL,ADRESS) values ('15336247','abidos','aminos','caissier','25648952','abid.aimen21@gmail.com','jaafer');
Insert into AYMEN.EM (CIN,NOM,PRENOM,TYPEFONCTION,TELEPHONE,EMAIL,ADRESS) values ('11036974','krichen','nouri','femme de menage','74003958','noureddine.krichen@esprit.tn','sfax');
REM INSERTING into AYMEN.FC
SET DEFINE OFF;
Insert into AYMEN.FC (TYPEFONCTION,SALAIRE,JOURDETRAVAIL,HEUREDEDEBUT,HEUREDEFIN,DEBUTDECONGE,FINDECONGE) values ('cuisinier','2000','mardi','08:00','12:00',to_date('01/01/00','DD/MM/RR'),to_date('01/01/00','DD/MM/RR'));
Insert into AYMEN.FC (TYPEFONCTION,SALAIRE,JOURDETRAVAIL,HEUREDEDEBUT,HEUREDEFIN,DEBUTDECONGE,FINDECONGE) values ('serveur','1000','lundi','08:30','14:00',to_date('01/01/00','DD/MM/RR'),to_date('01/01/00','DD/MM/RR'));
Insert into AYMEN.FC (TYPEFONCTION,SALAIRE,JOURDETRAVAIL,HEUREDEDEBUT,HEUREDEFIN,DEBUTDECONGE,FINDECONGE) values ('Chef','3000','Toutes la semaine','09:00','18:00',to_date('01/01/00','DD/MM/RR'),to_date('01/01/00','DD/MM/RR'));
Insert into AYMEN.FC (TYPEFONCTION,SALAIRE,JOURDETRAVAIL,HEUREDEDEBUT,HEUREDEFIN,DEBUTDECONGE,FINDECONGE) values ('livreur','2000','samedi et dimanche','15:30','22:00',to_date('01/01/00','DD/MM/RR'),to_date('01/01/00','DD/MM/RR'));
Insert into AYMEN.FC (TYPEFONCTION,SALAIRE,JOURDETRAVAIL,HEUREDEDEBUT,HEUREDEFIN,DEBUTDECONGE,FINDECONGE) values ('caissier','1000','Toute la semaine','08:00','18:00',to_date('04/01/00','DD/MM/RR'),to_date('09/01/00','DD/MM/RR'));
Insert into AYMEN.FC (TYPEFONCTION,SALAIRE,JOURDETRAVAIL,HEUREDEDEBUT,HEUREDEFIN,DEBUTDECONGE,FINDECONGE) values ('femme de menage','1000','lundi','07:00','11:00',to_date('11/01/00','DD/MM/RR'),to_date('12/01/00','DD/MM/RR'));
REM INSERTING into AYMEN.FOURNISSEUR
SET DEFINE OFF;
REM INSERTING into AYMEN.MATERIEL
SET DEFINE OFF;
REM INSERTING into AYMEN.PLAT
SET DEFINE OFF;
REM INSERTING into AYMEN.PRODUIT
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index FC_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AYMEN"."FC_PK" ON "AYMEN"."FC" ("TYPEFONCTION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table FC
--------------------------------------------------------

  ALTER TABLE "AYMEN"."FC" ADD CONSTRAINT "FC_PK" PRIMARY KEY ("TYPEFONCTION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AYMEN"."FC" MODIFY ("TYPEFONCTION" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table EM
--------------------------------------------------------

  ALTER TABLE "AYMEN"."EM" ADD CONSTRAINT "EM_FK1" FOREIGN KEY ("TYPEFONCTION")
	  REFERENCES "AYMEN"."FC" ("TYPEFONCTION") ENABLE;
